### ISSUE TITLE
Selfupdate not working.

### ISSUE THREAD

**Issue by srcr** [rhysd/go-github-selfupdate#28]
Hi, your notes-cli looked like an interesting tool, but I found that it depends on your selfupdate tool my assumption is that the GO function changed and your tool hasn't perhaps it is something you can fix.

My go version is go1.14.1  below is the error message I get.

```
go/src/github.com/rhysd/go-github-selfupdate/selfupdate/update.go:59:67: not enough arguments in call to up.api.Repositories.DownloadReleaseAsset
        have (context.Context, string, string, int64)
        want (context.Context, string, string, int64, *http.Client)
go/src/github.com/rhysd/go-github-selfupdate/selfupdate/update.go:81:87: not enough arguments in call to up.api.Repositories.DownloadReleaseAsset
        have (context.Context, string, string, int64)
        want (context.Context, string, string, int64, *http.Client)
```

**Comment by michaelbirdflyt** [comment]
I have encountered the same issue. 
There is an http.Client expected in the go-github library [here](https://github.com/google/go-github/blob/e4b511744f5bbb020d00e172a284468137d4e5fc/github/repos_releases.go#L275 )

Added in [this PR](https://github.com/google/go-github/commit/75ddd505ad1c4d7c2d0bd0c5e0ef4e753907fe6a#diff-75909ea88d89029fe24198471fc539ae)

**Comment by rhysd** [comment]
#29 fixed this.
