### ISSUE TITLE
go.mod question

### ISSUE THREAD

**Issue by hahwul** [rhysd/go-github-selfupdate#30]
Hi @rhysd 
I left it as an issue because I had a question.
First of all, thank you so much for making a good module!

I'm using your module on my tools, but there's a problem. After adding go-github-selfupdate to go.mod, the following error occurred when installing my tool as go get. 

my go.mod: https://github.com/hahwul/dalfox/blob/master/go.mod
error
```
$ go get -u github.com/hahwul/dalfox
package github.com/google/go-github/v30/github: cannot find package "github.com/google/go-github/v30/github" in any of:
	/usr/local/Cellar/go/1.12.4/libexec/src/github.com/google/go-github/v30/github (from $GOROOT)
	/Users/kakao/go/src/github.com/google/go-github/v30/github (from **$GOPATH)**
```
There's no problem except go get. (both go install and binary build are possible)
Do you know anything? I need help!

**Comment by rhysd** [comment]
Closing this because the problem seemed to be resolved yet: https://github.com/google/go-github/issues/1549
